/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.3/samples
 */
plugins {
    // Поддержка запуска из командной строки
  id("se.patrikerdes.use-latest-versions") version "0.2.18"
  id("com.github.ben-manes.versions") version "0.50.0"
  application
}

repositories {
    // Подключаем автоматическая работа с репозиторием Maven Central
    mavenCentral()
}

// Для плагина application указываем главный класс приложения
application {
    // Входная точка
    mainClass.set("io.hexlet.example.App")
}
dependencies {
    //зависимость
    implementation("org.apache.commons:commons-lang3:3.14.0")
}
